/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val logback_classic: String = "ch.qos.logback:logback-classic:_"

    const val cucumber_java8: String = "io.cucumber:cucumber-java8:_"

    const val cucumber_junit: String = "io.cucumber:cucumber-junit:_"
}
